package com.rfhoodrdm.asterage2.gui;

import java.awt.image.BufferedImage;

import lombok.Getter;
import lombok.Setter;

public enum Image {
	// Title screen graphics
	DEFAULT("DEFAULT.png"), TITLE_GRAPHIC("TITLE_GRAPHIC.png"),
	GAME_SELECTOR_ICON_WHITE("GAME_SELECTOR_ICON_WHITE.png"), NO_IMAGE("NO_IMAGE.png"),

	// Asterage 1 graphics
	EXTRA_LIFE_ICON("EXTRA_LIFE_ICON.png"), SHIP_SPRITE("SHIP_SPRITE.png"),
	DAMAGED_SHIP_SPRITE("DAMAGED_SHIP_SPRITE.png"), PLAYER_BULLET("PLAYER_BULLET.png"),
	PLAYER_DEBRIS("PLAYER_DEBRIS.png"), ENEMY_BULLET("ENEMY_BULLET.png"), ENEMY_DEBRIS("ENEMY_DEBRIS.png"),
	TROLL_SCOUT("TROLL_SCOUT.png"), TROLL_MOTHERSHIP("TROLL_MOTHERSHIP.png"), TROLL_POD("TROLL_POD.png"),
	LARGE_ASTEROID("LARGE_ASTEROID.png"), MEDIUM_ASTEROID("MEDIUM_ASTEROID.png"), SMALL_ASTEROID("SMALL_ASTEROID.png"),
	TROLL_1("TROLL_1.png"), TROLL_2("TROLL_2.png"), POD_SPRITE("POD_SPRITE.png"), MYTHICITE("MYTHICITE.png"),

	// AsteRAGE 2 Graphics:
	A2_PLAYER_SHIP("A2_PLAYER_SHIP.png"), A2_TROLL_MINING_POD("A2_TROLL_MINING_POD.png"),

	A2_ASTEROID_SMALL_WHITE("A2_ASTEROID_SMALL_WHITE.png"), A2_ASTEROID_MEDIUM_WHITE("A2_ASTEROID_MEDIUM_WHITE.png"),
	A2_ASTEROID_LARGE_WHITE("A2_ASTEROID_LARGE_WHITE.png"),

	A2_ASTEROID_SMALL_TAN("A2_ASTEROID_SMALL_TAN.png"), A2_ASTEROID_MEDIUM_TAN("A2_ASTEROID_MEDIUM_TAN.png"),
	A2_ASTEROID_LARGE_TAN("A2_ASTEROID_LARGE_TAN.png"),

	A2_ASTEROID_SMALL_RED("A2_ASTEROID_SMALL_RED.png"), A2_ASTEROID_MEDIUM_RED("A2_ASTEROID_MEDIUM_RED.png"),
	A2_ASTEROID_LARGE_RED("A2_ASTEROID_LARGE_RED.png"),

	A2_ASTEROID_SMALL_PURPLE("A2_ASTEROID_SMALL_PURPLE.png"),
	A2_ASTEROID_MEDIUM_PURPLE("A2_ASTEROID_MEDIUM_PURPLE.png"),
	A2_ASTEROID_LARGE_PURPLE("A2_ASTEROID_LARGE_PURPLE.png"),

	A2_PLASMA_BOLT_PLAYER("A2_PLASMA_BOLT_PLAYER.png"), A2_PLASMA_BOLT_ENEMY("A2_PLASMA_BOLT_ENEMY.png"),

	A2_HOMING_MISSILE_PLAYER("A2_HOMING_MISSILE_PLAYER.png"), A2_HOMING_MISSILE_TROLL("A2_HOMING_MISSILE_TROLL.png"),

	A2_WARP_OUT_GRAPHIC("A2_WARP_OUT_GRAPHIC.png"),

	// Power-up menu icons
	A2_POWER_UP_ICON_DECELERATION("A2_POWER_UP_ICON_DECELERATION.png"),
	A2_POWER_UP_ICON_DECELERATION_SELECTED("A2_POWER_UP_ICON_DECELERATION_SELECTED.png"),
	A2_POWER_UP_ICON_MULTISHOT("A2_POWER_UP_ICON_MULTISHOT.png"),
	A2_POWER_UP_ICON_MULTISHOT_SELECTED("A2_POWER_UP_ICON_MULTISHOT_SELECTED.png"),

	A2_POWER_UP_ICON_HOMING_MISSILE("A2_POWER_UP_ICON_HOMING_MISSILE.png"),
	A2_POWER_UP_ICON_HOMING_MISSILE_SELECTED("A2_POWER_UP_ICON_HOMING_MISSILE_SELECTED.png"),
	A2_POWER_UP_ICON_SHIELD_GENERATOR("A2_POWER_UP_ICON_SHIELD_GENERATOR.png"),
	A2_POWER_UP_ICON_SHIELD_GENERATOR_SELECTED("A2_POWER_UP_ICON_SHIELD_GENERATOR_SELECTED.png"),

	A2_POWER_UP_ICON_POINTS("A2_POWER_UP_ICON_POINTS.png"),
	A2_POWER_UP_ICON_POINTS_SELECTED("A2_POWER_UP_ICON_POINTS_SELECTED.png"),

	// Ship system icons
	A2_SYSTEM_ICON_DECELERATION_LEVEL_0("A2_SYSTEM_ICON_DECELERATION_LEVEL_0.png"),
	A2_SYSTEM_ICON_DECELERATION_LEVEL_1("A2_SYSTEM_ICON_DECELERATION_LEVEL_1.png"),
	A2_SYSTEM_ICON_DECELERATION_LEVEL_2("A2_SYSTEM_ICON_DECELERATION_LEVEL_2.png"),

	A2_SYSTEM_ICON_HOMING_MISSILE_LEVEL_0("A2_SYSTEM_ICON_HOMING_MISSILE_LEVEL_0.png"),
	A2_SYSTEM_ICON_HOMING_MISSILE_LEVEL_1("A2_SYSTEM_ICON_HOMING_MISSILE_LEVEL_1.png"),
	A2_SYSTEM_ICON_HOMING_MISSILE_LEVEL_2("A2_SYSTEM_ICON_HOMING_MISSILE_LEVEL_2.png"),

	A2_SYSTEM_ICON_SHIELD_GENERATOR_LEVEL_0("A2_SYSTEM_ICON_SHIELD_GENERATOR_LEVEL_0.png"),
	A2_SYSTEM_ICON_SHIELD_GENERATOR_LEVEL_1("A2_SYSTEM_ICON_SHIELD_GENERATOR_LEVEL_1.png"),
	A2_SYSTEM_ICON_SHIELD_GENERATOR_LEVEL_2("A2_SYSTEM_ICON_SHIELD_GENERATOR_LEVEL_2.png"),

	A2_SYSTEM_ICON_MULTISHOT_LEVEL_0("A2_SYSTEM_ICON_MULTISHOT_LEVEL_0.png"),
	A2_SYSTEM_ICON_MULTISHOT_LEVEL_1("A2_SYSTEM_ICON_MULTISHOT_LEVEL_1.png"),
	A2_SYSTEM_ICON_MULTISHOT_LEVEL_2("A2_SYSTEM_ICON_MULTISHOT_LEVEL_2.png"),

	A2_SYSTEM_ICON_SONIC_DISRUPTOR_DISABLED("A2_SYSTEM_ICON_SONIC_DISRUPTOR_DISABLED.png"),
	A2_SYSTEM_ICON_SONIC_DISRUPTOR_ENABLED("A2_SYSTEM_ICON_SONIC_DISRUPTOR_ENABLED.png"),

	A2_SYSTEM_ICON_GRAVITY_NET_DISABLED("A2_SYSTEM_ICON_GRAVITY_NET_DISABLED.png"),
	A2_SYSTEM_ICON_GRAVITY_NET_ENABLED("A2_SYSTEM_ICON_GRAVITY_NET_ENABLED.png"),

	// power up icons
	A2_POWER_UP_GRAVITY_NET("A2_POWER_UP_GRAVITY_NET.png"),
	A2_POWER_UP_SHIELD_RESTORATION("A2_POWER_UP_SHIELD_RESTORATION.png"),
	A2_POWER_UP_SONIC_DISRUPTOR("A2_POWER_UP_SONIC_DISRUPTOR.png"), A2_MYTHICITE("A2_MYTHICITE.png");

	@Getter
	private String filename;
	
	@Getter
	@Setter
	private BufferedImage image;

	Image(String passedFilename) {
		this.filename = passedFilename;
	}

}
