/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;
import state.TitleState;
import javax.swing.JLabel;
import javax.swing.JButton;
import java.awt.Dimension;
import gui.templates.PanelTemplate;
import java.awt.Color;
import java.awt.Font;
import javax.swing.SwingConstants;
import javax.swing.ImageIcon;

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
public class TitleGameMenu
extends PanelTemplate
{
	/*	**********************************************************************
		*******************			Data Members			******************
		********************************************************************** */
	
	public static final int titleMenuWidth = 410;
	public static final int titleMenuHeight = 150;
	
	JLabel asterage1MenuOption;
	JLabel asterage2MenuOption;
	
	JButton asterage1MenuSelectionIndicator;
	JButton asterage2MenuSelectionIndicator;
	
	final int menuOptionWidth = 260;
	final int menuOptionHeight = 75;
	final int menuIndicatorWidth = 50;
	final int menuIndicatorHeight = 50;
	
	final Dimension menuOptionDimension = new Dimension (menuOptionWidth, menuOptionHeight);
	final Dimension menuSelectionIndicatorDimension = new Dimension ( menuIndicatorWidth, menuIndicatorHeight) ;
	
	final int firstRowX = 25;
	final int firstRowY = 20;
	final int secondRowX = 100;
	final int secondRowY = 80;
	
	Color menuTextColor = new Color ( 255, 0, 0);
	Font menuTextFont = new Font("Skia", Font.BOLD, 22);
	
	/*	**********************************************************************
		********************		Constructor				******************
		********************************************************************** */
	/**
	 * Constructor
	 */
	public TitleGameMenu ()
	{
		//set up the GUI components.
		this.setLayout ( null );		//honor the coordinates of sub components.
		int upperLeftX = (GUI.panelWidth/2) - ( titleMenuWidth / 2 );
		int upperLeftY = 500;
		this.setBounds ( upperLeftX, upperLeftY, titleMenuWidth, titleMenuHeight);
		
		asterage1MenuOption = new JLabel();
		asterage2MenuOption = new JLabel();
		asterage1MenuSelectionIndicator = new JButton( new ImageIcon (GUI.Image.GAME_SELECTOR_ICON_WHITE.getImage() ) );
		asterage2MenuSelectionIndicator = new JButton( new ImageIcon (GUI.Image.GAME_SELECTOR_ICON_WHITE.getImage() ) );
		asterage1MenuSelectionIndicator.setBorderPainted(false);
		asterage2MenuSelectionIndicator.setBorderPainted(false);
		asterage1MenuSelectionIndicator.setVisible(false);
		asterage2MenuSelectionIndicator.setVisible(false);
		asterage1MenuSelectionIndicator.setContentAreaFilled(false);
		asterage2MenuSelectionIndicator.setContentAreaFilled(false);
		
		asterage1MenuOption.setText("AsteRAGE Classic");
		asterage1MenuOption.setForeground(menuTextColor);
		asterage1MenuOption.setFont ( menuTextFont );
		asterage1MenuOption.setVerticalTextPosition(SwingConstants.TOP); 
		asterage2MenuOption.setText("AsteRAGE 2: to Infinity!");
		asterage2MenuOption.setForeground(menuTextColor);
		asterage2MenuOption.setFont ( menuTextFont );
		asterage2MenuOption.setVerticalTextPosition(SwingConstants.TOP); 
		asterage1MenuOption.setBounds( secondRowX, secondRowY, menuOptionWidth, menuOptionHeight );
		asterage2MenuOption.setBounds( secondRowX, firstRowY, menuOptionWidth, menuOptionHeight );
		
		asterage1MenuSelectionIndicator.setBounds( firstRowX, secondRowY, menuIndicatorWidth, menuIndicatorHeight );
		asterage2MenuSelectionIndicator.setBounds( firstRowX, firstRowY, menuIndicatorWidth, menuIndicatorHeight );
		asterage1MenuSelectionIndicator.setFocusable(false);	//can't receive focus
		asterage2MenuSelectionIndicator.setFocusable(false);	//can't receive focus.
		
		this.add(asterage1MenuOption);
		this.add(asterage2MenuOption);
		this.add(asterage1MenuSelectionIndicator);
		this.add(asterage2MenuSelectionIndicator);
		
	} //end function TitleGameMenu contrusctor
	/*	**********************************************************************
		********************		Class Interface			******************
		********************************************************************** */
	public void refreshTitleGameMenu(TitleState.GAME_SELECTION currentGameSelection)
	{
		//show and hide the appropriate buttons.
		switch ( currentGameSelection )
		{
			case ASTERAGE1:
				asterage1MenuSelectionIndicator.setVisible( true );
				asterage2MenuSelectionIndicator.setVisible( false );
				break;
			case ASTERAGE2:
				asterage1MenuSelectionIndicator.setVisible( false );
				asterage2MenuSelectionIndicator.setVisible( true );
				break;
		} //end function 
	} //end function refreshTitleGameMenu
	
	/*	**********************************************************************
		********************		Functionality			******************
		********************************************************************** */
}
