package com.rfhoodrdm.asterage2.sounds;

public enum SoundEvent {
	// Title screen events.
	TITLE_SCREEN_MENU_OPTION_CHANGED, 
	TITLE_SCREEN_MENU_GAME_SELECTED,

	// Asterage 1 game events.
	PLAYER_FIRES_BULLET, 
	ENEMY_FIRES_BULLET, 
	ASTEROID_IMPACT, 
	PLAYER_SHIELD_IMPACT, 
	ENEMY_SHIELD_IMPACT, 
	REWARD_EARNED,
	PLAYER_SHIP_APPEARS,
	ENEMY_APPEARS, 
	BIG_ENEMY_APPEARS, 
	PLAYER_DESTROYED, 
	SMALL_ENEMY_DESTROYED, 
	GIANT_LASER_FIRE,
	PLAYER_SHIP_DESTROYED,
	ENEMY_SHIP_DESTROYED,
	ALIEN_EMERGES, 
	WEAPON_POD_DESTROYED,
	TRACTOR_BEAM_DEPLOYED,

	// ASTERAGE 2 game events;
	A2_ASTEROID_IMPACT,
	A2_ENEMY_PLASMA_BOLT_FIRE, 
	A2_EXTRA_LIFE_AWARDED, 
	A2_MYTHICITE_PICKUP,
	A2_PLAYER_DESTROYED,
	A2_PLAYER_HOMING_MISSILES_FIRED, 
	A2_PLAYER_PLASMA_BOLT_FIRE, 
	A2_PLAYER_PURCHASE_ACCEPTED,
	A2_PLAYER_PURCHASE_DENIED,
	A2_PLAYER_SHIELD_IMPACT,
	A2_PLAYER_SONIC_DISRUPTOR_ACTIVE, 
	A2_PLAYER_SPAWNS, 
	A2_SPECIAL_POWERUP_PICKUP,
	A2_TROLL_APPEARS, 
	A2_TROLL_DESTROYED, 
	A2_TROLL_LASER_FIRED,
	A2_TROLL_SHIELD_IMPACT, 
	A2_TROLL_MOTHERSHIP_APPEARS,
	A2_VICTORY_FANFARE, 
	A2_WARPING_OUT;
}
